name: "Auto card assign"
on:
  project_card:
    types: ["created", "moved", "converted"]

jobs:
  card_assign:
    runs-on: ubuntu-latest
    steps:
      - uses: 1natsu172/github-action-auto-card-assign@v1
        id: card_assign_action
        with:
          # github_token: "${{ secrets.GITHUB_TOKEN }}"
          config: "project-card-assign.yml"
